export enum WorkerMessageType {
  INIT = "INIT",
  RESIZE = "RESIZE",
  CACHE_IMAGE = "CACHE_IMAGE",
  RENDER_PAGE = "RENDER_PAGE",
  CLEAR_CACHE = "CLEAR_CACHE",
  TERMINATE = "TERMINATE",
  RENDERED = "RENDERED",
  CACHE_PRUNED = "CACHE_PRUNED",
  ERROR = "ERROR",
}
