import type { Metadata } from "next";
import "./globals.css";
import manrope from "@/assets/fonts";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Glide",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script src="https://unpkg.com/react-scan/dist/auto.global.js" async />
      </head>
      <body
        className={cn(
          "antialiased h-svh w-full font-manrope text-white",
          manrope.variable
        )}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
