import type { Metadata } from "next";
import "./globals.css";
import manrope from "@/assets/fonts";
import { cn } from "@/lib/utils";
import { Toaster as SonnerToaster } from "@/components/ui/sonner";
import { ToastProvider as Toaster } from "@/components/ui/toast";
import { TooltipProvider } from "@/components/ui/tooltip";

export const metadata: Metadata = {
  title: "Glide",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* <script src="https://unpkg.com/react-scan/dist/auto.global.js" async /> */}
      </head>
      <body
        className={cn(
          "antialiased h-svh w-full font-manrope text-white",
          manrope.variable
        )}
      >
        <TooltipProvider delayDuration={0}>{children}</TooltipProvider>
        <Toaster />
        <SonnerToaster
          toastOptions={{
            classNames: {
              toast:
                "rounded-xl gap-2 text-base text-white font-semibold py-4 px-6",
              title: "font-semibold text-background",
              icon: "text-white",
              success: "bg-success border-border-success",
              warning: "bg-warning border-border-warning",
              error: "bg-error border-border-error",
            },
          }}
        />
      </body>
    </html>
  );
}
